version: 2
project_name: openhue

before:
  hooks:
    - go mod tidy

universal_binaries:
  - id: openhue
    replace: true

builds:
  - id: openhue
    binary: openhue
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - id: openhue
    image_templates:
      - openhue/cli:latest
      - openhue/cli:{{ .Tag }}
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/openhue/openhue-cli"

brews:
  - name: openhue-cli
    homepage: https://github.com/openhue/homebrew-cli
    description: OpenHue CLI is a command-line interface for interacting with Philips Hue smart lighting systems
    license: Apache License 2.0
    repository:
      owner: openhue
      name: homebrew-cli
      token: "{{ .Env.OPENHUE_HOMEBREW_CLI_TOKEN }}"

archives:
  - id: openhue
    formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
